### ISSUE TITLE
parameter properties -- always or never

### ISSUE THREAD

**Issue by aervin** [fimbullinter/wotan#167]
TSLint's `no-parameter-properties` doesn't really do it for me. I'd like a way to enforce that one or the other is used project-wide. Does this already exist as part of a separate rule package?

**Comment by ajafff** [comment]
This seems like a good addition.

Here are my initial thoughts about the requirements. Feedback is very much appreciated.

**never**:
* any parameter property is forbidden
* fairly easy to detect: look for constructors with body, loop though the parameters and check for modifiers
* autofixing should be pretty easy:
  * remove modifiers from parameters
  * add property declaration (right before the constructor) with the modifiers of the parameter
  * add an assignment at the beginning of the constructor
    * doesn't need to handle ordering, as parameter property initializers cannot access each other
    * after the call to `super()` if present
      * `super()` needs to be the first statement if there are parameter properties, so there's no need for special handling

**always**:
* *always* sounds a bit like "every property needs to be a parameter property" or "every constructor parameter needs to be a parameter property"
  * maybe we can come up with a better option name: `prefer`, `where-possible`, ...
* detecting:
  * first statement in the body needs to be `super();` (optionally with parameters) when extending another class
  * property with the same name and type as a parameter exists
    * probably needs type information
    * how to handle non-public properties that often have an underscore prefix?
  * property is not initialized
  * property is only assigned once with the parameter
    * assignment should be directly in the constructor body, not nested in IfStatement or similar
    * assignment is located before statements with side effects(?) to prevent changing runtime behavior
  * parameter is not modified before the assignment
  * parameter is an identifier, no destructuring allowed (yet)
* autofixing:
  * remove the property
  * remove the assignment
  * add the correct modifiers to the parameter

**consistent**:
* if all parameters of a constructor can be parameter properties, enforce parameter properties, otherwise forbid them
* I recall reading this as feature request in a TSLint issue

**Comment by aervin** [comment]
The approach to `never` seems straightforward like you said. My only thought is, could the fixer clash with member ordering?

On `always`:

* I agree the config option name could be improved. Or do we need any other config option besides `never`?
```yaml
# prefer/when-possible
rules:
  parameter-properties: error

# never
rules:
  parameter-properties:
    severity: error
    options:
      never: true
```

I'm not sure how intuitive this is...

I think you've addressed all the issues I can think of for detecting/fixing `when-possible` param props. I'd consider it a big win if we can catch these simple cases:
```ts
class HelloWorld {
    public propA: string;
    public propB: SomeType;
    public propC: string[];

    constructor(propA: string, propB: SomeType, propC: string[]) {
        // simple assignment to member w/ exact name/type
        this.propA = propA; // error - use a parameter property rather than assigning to members in the constructor body
        this.propB = propB; // error - use a parameter property rather than assigning to members in the constructor body
        // confusing code, but leave this alone (as you mentioned I think)
        this.propC = propC.filter(s => s === 'hello world!');
    }
}
```

This sort of thing strikes me as very hard to detect. Maybe you have some insight:
```ts
constructor(propA: string[]) {
    propA.reverse();
    // maybe some other code in here...
    this.propA = propA;
}
```

I hadn't considered the consistency issues you bring up, but I think I agree about enforcing param props _only_ in the event that all props can be param props. In the end, I'm after consistency at the `class` level. :+1:

**Comment by ajafff** [comment]
> This sort of thing strikes me as very hard to detect. Maybe you have some insight

I would probably choose the following approach:

* iterate through all statements in the constructor body
  * skip the first `super()`
  * if statement is *not* an ExpressionStatement containing a BinaryExpression with operatorToken === EqualsToken: return false
  * if statement is the assignment of the property we are looking for: return true
  * if BinaryExpression.left or BinaryExpression.right has side effects (`tsutils.hasSideEffects`): return false

Unfortunately that will also bail on logging or other unrelated  statements:

```ts
constructor(propA: string[]) {
    console.log('constructor called');
    // or
    ++instanceCount;
    // will not have lint error
    this.propA = propA;
}
```

**Comment by ajafff** [comment]
Regarding the options I would prefer to have an option to explicitly enable `"prefer"` mode:

```yaml
rules:
  parameter-properties:
    options:
      mode: prefer/never/consistent
```

Maybe we could drop the 'mode' property and have it as top level string option instead of an object.
But that requires users to rewrite their config if we ever add another config option. And the rule needs to add additional code to convert legacy options.

**Comment by aervin** [comment]
The config you're suggesting seems just fine to me. I think it makes sense to default to object config whenever possible. Updating legacy configs in TSLint rules was a real pain point. Defaulting to object saves users and devs from a lot of hassle.

**Comment by aervin** [comment]
> property is only assigned once with the parameter

For the initial implementation, how about making sure the prop is only referenced once within the constructor body, and that the prop is the left-hand side of a binary expression? Or is this too conservative?

Out of curiosity, is there a means of flattening portions of the node tree: `this.context.getFlatAst(constructorBody)`?

**Comment by ajafff** [comment]
> For the initial implementation, how about making sure the prop is only referenced once within the constructor body, and that the prop is the left-hand side of a binary expression

Actually it's only required that the first reference to the property is the LHS of a binary expression, where the RHS is the property. All following uses don't matter.
But your suggestion is seems fine for the initial implementation.

> Out of curiosity, is there a means of flattening portions of the node tree: `this.context.getFlatAst(constructorBody)`?

I'm wondering what your use case is? You need to find the AST node first. Typically you find the node by iterating the already flattened AST or by looking up the node at a certain position using `WrappedNode`. The latter can be used as linked list by using `next` or `skip` properties.

Note that you cannot simply iterate through all nodes of the constructor body. You need to skip subtrees of nested functions and classes that have their own `this` reference.

**Comment by aervin** [comment]
@ajafff Just felt like that sort of thing would've been useful in the past, but you're right, not useful here. 

Do constructor overloads throw a wrench into the works at all?

**Comment by ajafff** [comment]
Constructor overloads should simply be ignored. They cannot contain parameter properties.
