### ISSUE TITLE
npm inconsistency

### ISSUE THREAD

**Issue by ljani** [fimbullinter/wotan#258]
Currently if I install the latest versions of `@fimbul/valtyr` (latest is `v0.8.0`) and `@fimbul/wotan` (latest is `v0.9.0`) from npm, I get the following warning:

```
npm WARN @fimbul/valtyr@0.8.0 requires a peer of @fimbul/wotan@^0.8.0 but none is installed. You must install peer dependencies yourself.
```

I think you meant to either publish `valtyr@0.8.1` or `valtyr@0.9.0` as you have [updated the dependency](https://github.com/fimbullinter/wotan/commit/0cfd70d8e603f464ae420473e15811fcbd368458#diff-c3173d5bb2e2e30717267df196d83d3b).

As a workaround I can downgrade `wotan` to `0.8.0`.

**Comment by ajafff** [comment]
Thanks for the report. I noticed this too, but forgot to investigate.

It turns out in the `0.x.y` version range the caret selector (`^`) acts like tilde (`~`).
That means this is only a problem until the first "stable" semver version is published.

In fact everything still works fine, it's just npm (and yarn) that complains about a version mismatch.

For the time being I will probably update the release script to publish a new version of all packages as long as we're in the `0.x.y` range.

**Comment by ljani** [comment]
Yes, the `0.x` versions are considered major versions by the semver spec similar to eg. `1.0`. I did mention this in my comment at first, but I removed it, because it seemed that you already knew this, as you did bump the dependency, but didn't publish it. Sorry for that!

Thanks.

**Comment by ajafff** [comment]
> it seemed that you already knew this, as you did bump the dependency, but didn't publish it.

Yeah, I kinda experienced it because yarn was installing the packages from the registry and not from the monorepo. Therefore I updated the version in every dependent package. That fixed my dev workflow. Unfortunately I never thought about the need to publish them.

I updated the release script in 9dfa31eda5e4f72e249ece2c99aa66702e9857a7. I'll publish a new release shortly.
