### ISSUE TITLE
TypeScript LanguageService plugin

### ISSUE THREAD

**Issue by dcecile** [fimbullinter/wotan#408]
What do you think about having Wotan act as a plugin for the TypeScript compiler?

I'm imagining an ideal development loop that includes running lint checks continuously together with continuously compiling my TypeScript code.

If Wotan could be used as TypeScript compiler plugin (like [tslint-language-service](https://github.com/angelozerr/tslint-language-service/blob/master/src/index.ts)), then maybe this use case could be supported for `tsc --watch`, Webpack, or any other build system?

_Edit: Oops, it looks like TypeScript plugins aren't as powerful as I'd hoped, and wouldn't work for failing a `tsc` build..._
> _TypeScript Language Service Plugins ("plugins") are for changing the editing experience only. The core TypeScript language remains the same. Plugins can't add new language features such as new syntax or different typechecking behavior, and plugins aren't loaded during normal commandline typechecking or emitting._
> https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

**Comment by ajafff** [comment]
Thank you for the suggestion @dcecile. I think it's really helpful that you pointed out this doesn't change compiler behavior and is only relevant for editors.

This is somewhat related to #396 as the VSCode plugin could simply inject a language service plugin. Unfortunately it would need to change how the language service reads files (to allow for processors). In addition the linter runtime, each rule and every library (e.g. `tsutils`) used along the way needs to use the TypeScript version powering the language service instead of just using `import * as ts from 'typescript';`.

IIRC `tslint-language-service` also has some issues with regard to adding fixable diagnostics and uses a really hacky solution for that.

There's a somewhat related feature request https://github.com/Microsoft/TypeScript/issues/15589 to integrate linting functionality directly into TypeScript.

---

Regarding your initial request of integrating with the compiler:

That could be possible by wrapping `tsc`. Though that requires a lot of effort to make it work with `tsc --build` or `tsc --watch`. And even if one could get this to work, it would only be available as separate CLI tool that's not automatically picked up by other tools using the TypeScript compiler.

**Comment by ajafff** [comment]
The initial implementation is available in branch [ls-plugin](https://github.com/fimbullinter/wotan/tree/ls-plugin). It works, but has some rough edges.
It will be shipped in one of the next nightly builds.

Blocked on merging #482 
Related upstream issues for improved user experience: https://github.com/Microsoft/TypeScript/issues/28911, https://github.com/Microsoft/TypeScript/issues/28937, https://github.com/Microsoft/TypeScript/issues/28966, https://github.com/Microsoft/TypeScript/issues/28969

**Comment by ajafff** [comment]
For those willing to test the LanguageService plugin: In about 3 hours there will be a new nightly release that includes the plugin. The documentation is located here: https://github.com/fimbullinter/wotan/blob/master/packages/mithotyn/README.md

Note: to install the nightly release you need to execute

```sh
npm install --save-dev @fimbul/wotan@next @fimbul/mithotyn@next
# or
yarn add -D @fimbul/wotan@next @fimbul/mithotyn@next
```

Any kind of feedback is very much appreciated.

**Comment by ajafff** [comment]
@dcecile Thank you for the detailed feedback.

I had a similar problem with VSCode silently reverting my setting to using the bundled TypeScript version instead of the workspace version. I guess that happened during an update.
On a related note: you can enable TS Server logging in VSCode's settings and use `TypeScript: Open TS Server log` to open the log file.

To fix this I'm putting together a VSCode plugin to automatically inject the LanguageService plugin when using the bundled TypeScript version. #396 basically tracks that.
