### ISSUE TITLE
one-line-decorator interest

### ISSUE THREAD

**Issue by ciel** [fimbullinter/wotan#586]
I just created a tslint rule called “one-line-decorator” that enforces putting decorators on their own lines. Would you be interested in the code as a consideration for something to add to this? I’m not sure if it can be reproduced but you can likely tell at a glance.

I haven't used your suite yet, and I just spent so long on this rule that I'm hesitant to try something new but this all looks pretty awesome. 

It's not very good code, I just want to see if I can do the same thing in this suite before wasting a lot of time.

**Comment by ciel** [comment]
Actually here is the code. I just have to add the check against Parameters. Is this behavior possible in your engine?

https://gist.github.com/ciel/c5231b0a765c35f9596498462ba2817e

**Comment by ajafff** [comment]
> I just created a tslint rule [...] I’m not sure if it can be reproduced but you can likely tell at a glance.

The API for rules is almost the same. You can have a look at https://github.com/fimbullinter/wotan/blob/master/docs/writing-rules.md for more details.
Here are the main differences (I'll probably polish this up and publish it as a migration guide for TSLint rules):

* file names are dash-cased instead of camelCase and without the `Rule` suffix, so `oneLineDecoratorRule.ts` becomes `one-line-decorator.ts`
* export a `class Rule extends AbstractRule` (same as TSLint, but `AbstractRule` is imported from  `@fimbul/ymir`)
* inline all code of your walker (OneLineDecoratorCommand) into `Rule`
  * rename the `walk` method to `apply` and remove the `sourceFile` parameter (you can use `this.sourceFile` instead)
  * replace `this.addFailure` with `this.addFinding`
  * replace `Lint.Replacement.appendText` with `Replacement.append` (`Replacement` is imported from `@fimbul/ymir`)
* Bonus: you can get rid of `ts.forEachChild` completely by using `for (const node of this.context.getFlatAst() { if isDecorator(node) { this.visitDecorator(node) } }`
  * that even comes with a performance boost compared to `ts.forEachChild`

As an alternative you could have a look at [`@fimbul/bifrost`](https://github.com/fimbullinter/wotan/blob/master/packages/bifrost/README.md) which wraps your existing rule and makes it compatible with the other linter (TSLint -> Wotan or Wotan -> TSLint).

> Would you be interested in the code as a consideration for something to add to this?

Thank you for proposing this contribution. This project currently doesn't contain formatting rules. I'm not very keen on adding such rules and instead focus more on detecting actual bugs or bad practices.

However, you are welcome to publish a package with your custom rule to use it with Wotan. (You could even publish a package that can be consumed by TSLint and Wotan, see [`@fimbul/bifrost`](https://github.com/fimbullinter/wotan/blob/master/packages/bifrost/README.md) for compatibility and [tslint-consistent-codestyle](https://github.com/ajafff/tslint-consistent-codestyle) as an example.)

1. create `one-line-decorator.ts` as described above
2. compile it using `tsc`
3. create an `index.yaml` with the following content:
   ```yaml
   rulesDirectories:
     one-line-decorator: ./lib # the directory where your compiled rule is located or '.' if it's in the package root
   rules:
     one-line-decorator/one-line-decorator: true # if you want to enable the rule for every user of your package
   ```
4. create a package.json with the necessary content
   * `typescript` and `@fimbul/ymir` should be in peerDependencies (and in `devDependencies` for local development and testing)
5. publish as `one-line-decorator`
6. install in a project you want to use this rule
7. in `.wotanrc.yaml` of the consuming project add it to the `extends` array:
   ```yaml
   extends:
     - one-line-decorator
   ```
8. you're done

> I just have to add the check against Parameters. Is this behavior possible in your engine?

This is totally possible. The AST is the same TSLint uses. So you get the same information out of it.

In case you mean the rule options. They are configured in `.wotanrc.yaml` like so:

```yaml
rules:
  rule-name:
    options:
      foo: true
      bar: hello
```
You can access the raw options via `this.context.options`. If you extend `ConfigurableRule<OptionsType>` instead of `AbstractRule` you need to implement a `parseOptions` method where you normalize the raw options and access them via `this.options` later. See https://github.com/fimbullinter/wotan/blob/master/packages/mimir/src/rules/prefer-const.ts#L23-L31 for an example implementation.

Let me know if you are having trouble.
