### ISSUE TITLE
prefer-dot-notation: Don't warn when the accessed property is private/protected

### ISSUE THREAD

**Issue by AlCalzone** [fimbullinter/wotan#718]
In this case, using the proposed fix would cause TypeScript to error with `ts(2341)`

**Comment by ajafff** [comment]
So this would actually be the opposite of `no-restricted-property-access`?

That kinda makes sense. If you choose not to enable `no-restricted-property-access`, e.g. for tests, `prefer-dot-notation` should not introduce compile errors.

**Comment by AlCalzone** [comment]
I agree that these rules are somewhat similar but contradictory.
Maybe they could be made configurable, like https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/dot-notation.md which has configurable exceptions for private and protected properties.

**Comment by ajafff** [comment]
This is fixed in #742. Instead of making the behavior configurable, `prefer-dot-notation` now uses the same logic as `no-restricted-property-access` to determine whether dot notation is a compile error. This covers a lot more cases than simply accessing private and protected outside of their visibility.

**Comment by ajafff** [comment]
:tada: This issue has been resolved in version [v0.23.0](https://github.com/fimbullinter/wotan/releases/tag/v0.23.0) :tada:
